config/routes.rb
Rails.application.routes.draw do
  root 'home#landing_page'

  resources :portfolios
  resources :blogs do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :posts
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  mount_uploaders :photos, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :about)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing_page
    @portfolios = Portfolio.all 
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title, :about, {photos: []})
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to blog_posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :photo, :content, :date, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :blog_about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
<%= link_to 'Home', root_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container"> 
<h1>Blogs</h1>
<% @blogs.each do |blog| %>
    <div class="container">
<ul class="collection">

<h2><a href="<% blog_path(id: blog.id)%>"><p class="white-text text-darken-2"><%= blog.title %></p></a></h2>
        <p class="white-text"><%= blog.about %></p>
        <% blog.posts.each do |post|  %>
        <strong>Posts:</strong>
        <h3><%= post.date %></h3>
        <h1><%= post.title %></h1>
        <h6><%= post.content %></h6>
      </ul>
    <% end %>
      </div>
<% end %>

<br>
<%= link_to 'New Blog', new_blog_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>
<%= link_to 'Home', root_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>About:</strong>
  <%= @blog.about %>
</p>

<p>
  <strong>Posts:</strong>
  <% @blog.posts.each do |post|  %>
  <h3><%= post.date %></h3>
  <h2><%= post.title %></h2>
  <h6><%= post.content %></h6>
  <% end %>
</p>
<%= link_to 'New Post', new_blog_post_path(@blog) %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<%= link_to 'Home', root_path %>

app/views/home/landing_page.html.erb
<!-- big screen -->
<div id="landing_page">
  <div class="row animated rotateIn">
    <!-- quad 1 -->
    <div id="quadrant" class="col s12 m12 l6">
      <div class="section" style="background: url(/uploads/ibla/IMG_0883.GIF) center";>
        <div class="transparent center-align animated rotateInDownRight">
          <h1 class="transparent"><a href="#modal1">ABOUT</a></h1>
        </div>
      </div>
    </div>
    <!-- quad 2 -->
    <div id="quadrant" class="col s12 m12 l6">
      <div class="section" style="background: url(/uploads/ibla/IMG_0884.GIF) center">
        <div class="transparent center-align animated rotateInDownLeft">
          <h1 class="transparent"><%= link_to 'PORTFOLIO', portfolios_path %></a></h1>
        </div>
      </div>
    </div>
    <!-- quad 3 -->
    <div id="quadrant" class="col s12 m12 l6">
      <div class="section" style="background: url(/uploads/ibla/IMG_0885.GIF) center">
        <div class="transparent center-align animated rotateInUpRight">
          <h1 class="transparent"><%= link_to 'BLOG', blogs_path %></h1>
        </div>
      </div>
    </div>
    <div id="quadrant" class="col s12 m12 l6">
      <div class="section" style="background: url(/uploads/ibla/IMG_0891.GIF) center">
        <div class="transparent center-align animated rotateInUpLeft">
          <h1 class="transparent"><a href='#'>BOOKINGS</a></h1>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>About</h4>
    <p>About</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">close</a>
  </div>
</div>
        

app/views/layouts/_header.html.erb
<nav class="animated flipInY">
  <div class="nav-wrapper">
    <a href=<%= root_path %> class="brand-logo center">
    <p class='z-depth-5'><h1 style="background: url(/uploads/ibla/IMG_0892.GIF) 50%" class="white-text z-depth-5">IMBUED BEAUTY</h1></p>
    </a>
  </div>
</nav>
<nav>
    <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <a class="dropdown-button right hide-on-med-and-down" href="#!" data-activates="dropdown1"><i class="material-icons right">menu</i></a>
    <ul id="dropdown1" class="right hide-on-med-and-down dropdown-content">
      <li><a class="waves-effect waves-light btn" href="#modal1">About</a></li>
      <li><%= link_to 'Portfolio', portfolios_path %></li>
      <li><%= link_to 'Blog', blogs_path %></li>
      <li><a href="#">Bookings</a></li>
    </ul>
    <ul class="side-nav" id="mobile">
      <li><a class="waves-effect waves-light btn" href="#modal1">About</a></li>
      <li><%= link_to 'Portfolio', portfolios_path %></li>
      <li><%= link_to 'Blog', blogs_path %></li>
      <li><a href="#">Bookings</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImbuedBeautyRails</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%> 
  </head>
  <body>
  <%= render 'layouts/header' %>
  <br />
    <%= yield %>
  </body>
</html>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :portfolio_title %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about, id: :portfolio_about %>
  </div>

  <div class="field">
    <%= form.label :photos %><br>
    <%= form.file_field :photos, id: :portfolio_photos, multiple: true %>
    <%= form.hidden_field :photos_cache %>
    <% if portfolio.photos? %>
      <% portfolio.photos.each do |photo| %>
        <li>
          <%= image_tag photo.thumb.url %>
        </li>
        <%= form.label :remove_photos %>
        <%= form.check_box :remove_photos %>
      <% end %> 
    <% end %>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>
<%= link_to 'Home', root_path %>

app/views/portfolios/index.html.erb
<div class="container center">
<p id="notice">
  <%= notice %>
</p>
<!-- 
<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>About</th>
      <th>Photos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.title %></td>
        <td><%= portfolio.about %></td>
        <td><% portfolio.photos.each do |photo| %>
            <li><img src=<%= photo.thumb.url %>/> </li>
            <% end %>
        </td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>
<%= link_to 'Blogs', blogs_path %>
<%= link_to 'Home', root_path %>

 -->
<% @portfolios.each do |portfolio| %>

    <% portfolio.photos.each do |photo| %>
      <div class="row center">
        <div class="card hoverable animated fadeInRight">
          <div class="col s12 m6">
            <div class="card-image">
              <img width="400" src="<%= photo.url %>" />
            </div>
          </div>
        </div>
        <%  end %>
      </div>
  <% end %>
  </div>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>
<%= link_to 'Home', root_path %>

app/views/portfolios/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <strong>Title:</strong>
  <%= @portfolio.title %>
</p>
<p>
  <strong>About:</strong>
  <%= @portfolio.about %>
</p>
<p>
  <strong>Photos:</strong>
    <% @portfolio.photos.each do |photo| %>
      <li>
        <img src=<%= photo.url %>/>
      </li>
      <% end %>
</p>
<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
  <%= link_to 'Back', portfolios_path %>
  <%= link_to 'Blogs', blogs_path %>
  <%= link_to 'Home', root_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: blog_posts_path) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>
  <div class="field">
    <%= form.label :photo %><br>
    <%= form.file_field :photo %>
    <%= form.hidden_field :photo_cache %>
    <% if post.photo? %>
      <%= image_tag form.object.photo.thumb.url %>
      <%= form.label :remove_photo %>
      <%= form.check_box :remove_photo %>
    <% end %> 
  </div>  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :post_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', blog_post_path %>
<%= link_to 'Home', root_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.date %></td>
        <td><%= link_to 'Show', blog_post_path(id: post.id) %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(id: post.id) %></td>
        <td><%= link_to 'Destroy', blog_post_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_blog_post_path %>
<%= link_to 'Back', blogs_path %>
<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', blog_posts_path(:blog_id) %>
<%= link_to 'Home', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @post.photo.thumb.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@post) %> |
<%= link_to 'Back', blog_posts_path %>
<%= link_to 'Home', root_path %>